language: r
sudo: false
cache: packages

matrix:
  include:

  - os: linux
    dist: trusty
    r: oldrel

  - os: linux
    dist: trusty
    r: release
    after_success:
    - Rscript -e 'withr::with_envvar(c(NOT_CRAN="true"), covr::codecov())'
    
    
  - os: linux
    dist: trusty
    r: release
    r_github_packages: tidyverse/dplyr

  - os: linux
    dist: trusty
    r: devel

